name: CI

on: [push, pull_request]

jobs:
  default_tools:
    name: Test default system tools
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # https://github.com/kubkon/zld/issues/44
        # os: [macos, ubuntu, windows]
        os: [ macos-12, macos-latest, ubuntu-latest ]

    steps:
    - if: matrix.os == 'windows'
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v3
    - uses: goto-bus-stop/setup-zig@v2
      with:
        version: master
    - run: zig version
    - run: zig fmt --check src 
    - run: zig build test -Dhas-static -Dhas-zig -Dhas-objc-msgsend-stubs

  macos_11:
    name: Test macos 11.0
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
    - uses: goto-bus-stop/setup-zig@v2
      with:
        version: master
    - run: zig version
    - run: zig build test -Dhas-static -Dhas-zig

  gcc_musl:
    name: Test gcc with musl
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: goto-bus-stop/setup-zig@v2
      with:
        version: master
    - run: sudo apt-get install -y musl-tools
    - run: zig version
    - run: CC=musl-gcc zig build test -Dhas-static -Dmusl

  clang_glibc:
    name: Test clang with glibc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: goto-bus-stop/setup-zig@v2
      with:
        version: master
    - run: sudo apt-get install -y clang
    - run: zig version
    - run: CC=clang zig build test -Dhas-static -Dsystem-compiler=clang
